"""Escalation protocol for failed tasks.

When retries are exhausted, generates escalation reports for human review.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path


@dataclass
class AttemptRecord:
    """Record of a single retry attempt."""

    attempt_number: int
    phase: str
    error_message: str
    strategy: str
    duration_seconds: float
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class EscalationReport:
    """Escalation report for human review."""

    task_id: str
    task_description: str
    workflow_type: str
    attempts: list[AttemptRecord]
    suggested_actions: list[str]
    modified_files: list[str] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_markdown(self) -> str:
        """Convert report to markdown format."""
        lines = [
            "# Escalation Report",
            "",
            f"**Task ID:** `{self.task_id}`",
            f"**Created:** {self.created_at}",
            f"**Workflow:** {self.workflow_type}",
            "",
            "## Task Description",
            "",
            self.task_description,
            "",
            "## Retry Attempts",
            "",
            f"Total attempts: {len(self.attempts)}",
            "",
        ]

        for attempt in self.attempts:
            lines.extend(
                [
                    f"### Attempt {attempt.attempt_number}",
                    "",
                    f"- **Phase:** {attempt.phase}",
                    f"- **Strategy:** {attempt.strategy}",
                    f"- **Duration:** {attempt.duration_seconds:.1f}s",
                    f"- **Timestamp:** {attempt.timestamp}",
                    "",
                    "**Error:**",
                    "```",
                    attempt.error_message,
                    "```",
                    "",
                ]
            )

        if self.modified_files:
            lines.extend(
                [
                    "## Modified Files",
                    "",
                ]
            )
            for f in self.modified_files:
                lines.append(f"- `{f}`")
            lines.append("")

        lines.extend(
            [
                "## Suggested Actions",
                "",
            ]
        )
        for i, action in enumerate(self.suggested_actions, 1):
            lines.append(f"{i}. {action}")

        lines.extend(
            [
                "",
                "---",
                "",
                "*This report was auto-generated by ADW after exhausting retry attempts.*",
            ]
        )

        return "\n".join(lines)


def generate_escalation_report(
    task_id: str,
    task_description: str,
    workflow_type: str,
    attempts: list[AttemptRecord],
    modified_files: list[str] | None = None,
    output_dir: Path | None = None,
) -> EscalationReport:
    """Generate an escalation report for a failed task.

    Args:
        task_id: ADW task ID.
        task_description: Description of the task.
        workflow_type: Type of workflow (e.g., "sdlc", "standard").
        attempts: List of retry attempts.
        modified_files: Optional list of files modified during attempts.
        output_dir: Optional directory to write the report to.

    Returns:
        EscalationReport object.
    """
    # Analyze attempts to generate suggestions
    suggested_actions = _generate_suggestions(attempts, task_description)

    report = EscalationReport(
        task_id=task_id,
        task_description=task_description,
        workflow_type=workflow_type,
        attempts=attempts,
        suggested_actions=suggested_actions,
        modified_files=modified_files or [],
    )

    # Write to file if output_dir provided
    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        report_path = output_dir / "escalation.md"
        report_path.write_text(report.to_markdown())

    return report


def _generate_suggestions(
    attempts: list[AttemptRecord],
    task_description: str,
) -> list[str]:
    """Generate suggested actions based on failure patterns."""
    suggestions = []

    # Collect error messages for pattern matching
    errors = [a.error_message.lower() for a in attempts]

    # Check for common patterns
    if any("timeout" in e for e in errors):
        suggestions.append("Increase timeout or break task into smaller chunks")

    if any("import" in e or "module" in e for e in errors):
        suggestions.append("Check for missing dependencies or incorrect import paths")

    if any("permission" in e or "access denied" in e for e in errors):
        suggestions.append("Verify file/directory permissions and access rights")

    if any("syntax" in e for e in errors):
        suggestions.append("Review generated code for syntax errors")

    if any("test" in e or "assert" in e for e in errors):
        suggestions.append("Review test expectations and implementation alignment")

    if any("api" in e or "request" in e or "network" in e for e in errors):
        suggestions.append("Check API endpoints, authentication, and network connectivity")

    if any("memory" in e or "overflow" in e for e in errors):
        suggestions.append("Optimize memory usage or process data in smaller batches")

    # Always suggest manual review
    suggestions.append("Manually review the generated code and error messages")
    suggestions.append("Consider simplifying the task requirements")
    suggestions.append("Check if similar tasks have been completed successfully for reference")

    return suggestions


def save_escalation_report(
    report: EscalationReport,
    agents_dir: Path,
) -> Path:
    """Save escalation report to the agents directory.

    Args:
        report: The escalation report to save.
        agents_dir: Base directory for agent outputs.

    Returns:
        Path to the saved report.
    """
    task_dir = agents_dir / report.task_id
    task_dir.mkdir(parents=True, exist_ok=True)

    report_path = task_dir / "escalation.md"
    report_path.write_text(report.to_markdown())

    return report_path
